"""product billing, credit ledger, and reservations

Revision ID: 20260714_0012
Revises: 20260714_0011
"""

from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


revision = "20260714_0012"
down_revision = "20260714_0011"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("product_billing_catalog_versions", sa.Column("id", sa.String(36), primary_key=True), sa.Column("version_key", sa.String(100), nullable=False, unique=True), sa.Column("market", sa.String(8), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("effective_from", sa.DateTime(timezone=True)), sa.Column("effective_to", sa.DateTime(timezone=True)), sa.Column("created_by_user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("activation_reason", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("published_at", sa.DateTime(timezone=True)))
    op.create_index("ix_product_billing_catalog_active", "product_billing_catalog_versions", ["market", "currency", "status", "effective_from"])
    op.create_table("product_billing_offers", sa.Column("id", sa.String(36), primary_key=True), sa.Column("catalog_version_id", sa.String(36), sa.ForeignKey("product_billing_catalog_versions.id", ondelete="CASCADE"), nullable=False), sa.Column("code", sa.String(64), nullable=False), sa.Column("display_name", sa.String(200), nullable=False), sa.Column("offer_type", sa.String(24), nullable=False), sa.Column("amount_minor", sa.Integer(), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("billing_interval", sa.String(24)), sa.Column("credit_grant", sa.Integer(), nullable=False), sa.Column("active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("catalog_version_id", "code", name="uq_product_billing_offer_code"))
    op.create_index("ix_product_billing_offers_catalog_type", "product_billing_offers", ["catalog_version_id", "offer_type"])
    op.create_table("product_feature_credit_prices", sa.Column("id", sa.String(36), primary_key=True), sa.Column("catalog_version_id", sa.String(36), sa.ForeignKey("product_billing_catalog_versions.id", ondelete="CASCADE"), nullable=False), sa.Column("feature_key", sa.String(64), nullable=False), sa.Column("credit_cost", sa.Integer(), nullable=False), sa.Column("maximum_duration_minutes", sa.Integer()), sa.Column("change_reason", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("catalog_version_id", "feature_key", name="uq_product_feature_credit_price"))
    op.create_table("product_signup_trial_policies", sa.Column("id", sa.String(36), primary_key=True), sa.Column("policy_key", sa.String(80), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False), sa.Column("trigger", sa.String(40), nullable=False), sa.Column("credit_grant", sa.Integer(), nullable=False), sa.Column("valid_days", sa.Integer(), nullable=False), sa.Column("grants_per_user", sa.Integer(), nullable=False), sa.Column("policy_version", sa.String(80), nullable=False, unique=True), sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False), sa.Column("reason", sa.Text()), sa.Column("created_by_user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("product_billing_subscriptions", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("offer_id", sa.String(36), sa.ForeignKey("product_billing_offers.id", ondelete="RESTRICT"), nullable=False), sa.Column("provider", sa.String(40), nullable=False), sa.Column("provider_customer_id", sa.String(255)), sa.Column("provider_subscription_id", sa.String(255)), sa.Column("status", sa.String(24), nullable=False), sa.Column("current_period_reference", sa.String(255)), sa.Column("current_period_start", sa.DateTime(timezone=True)), sa.Column("current_period_end", sa.DateTime(timezone=True)), sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("provider", "provider_subscription_id", name="uq_product_billing_provider_subscription"))
    op.create_index("ix_product_billing_subscriptions_user_status", "product_billing_subscriptions", ["user_id", "status"])
    op.create_table("product_credit_accounts", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("status", sa.String(24), nullable=False), sa.Column("debt", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("product_credit_buckets", sa.Column("id", sa.String(36), primary_key=True), sa.Column("account_id", sa.String(36), sa.ForeignKey("product_credit_accounts.id", ondelete="CASCADE"), nullable=False), sa.Column("bucket_type", sa.String(24), nullable=False), sa.Column("source_reference", sa.String(255)), sa.Column("granted", sa.Integer(), nullable=False), sa.Column("available", sa.Integer(), nullable=False), sa.Column("reserved", sa.Integer(), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("account_id", "bucket_type", "source_reference", name="uq_product_credit_bucket_source"))
    op.create_index("ix_product_credit_buckets_account_expiry", "product_credit_buckets", ["account_id", "expires_at"])
    op.create_table("product_credit_ledger_entries", sa.Column("id", sa.String(36), primary_key=True), sa.Column("account_id", sa.String(36), sa.ForeignKey("product_credit_accounts.id", ondelete="RESTRICT"), nullable=False), sa.Column("bucket_id", sa.String(36), sa.ForeignKey("product_credit_buckets.id", ondelete="RESTRICT")), sa.Column("amount", sa.Integer(), nullable=False), sa.Column("entry_type", sa.String(24), nullable=False), sa.Column("balance_after", sa.Integer(), nullable=False), sa.Column("description", sa.String(500), nullable=False), sa.Column("reference_type", sa.String(80)), sa.Column("reference_id", sa.String(255)), sa.Column("idempotency_key", sa.String(255)), sa.Column("actor_user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("reason", sa.Text()), sa.Column("metadata_json", sa.JSON(), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("account_id", "idempotency_key", name="uq_product_credit_ledger_idempotency"), sa.CheckConstraint("amount <> 0", name="ck_product_credit_ledger_nonzero"))
    op.create_index("ix_product_credit_ledger_account_occurred", "product_credit_ledger_entries", ["account_id", "occurred_at"])
    op.create_index("ix_product_credit_ledger_reference", "product_credit_ledger_entries", ["reference_type", "reference_id"])
    op.create_table("product_credit_reservations", sa.Column("id", sa.String(36), primary_key=True), sa.Column("account_id", sa.String(36), sa.ForeignKey("product_credit_accounts.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("feature_key", sa.String(64), nullable=False), sa.Column("amount", sa.Integer(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("catalog_version_id", sa.String(36), sa.ForeignKey("product_billing_catalog_versions.id", ondelete="RESTRICT"), nullable=False), sa.Column("pricing_snapshot", sa.JSON(), nullable=False), sa.Column("reference_type", sa.String(80), nullable=False), sa.Column("reference_id", sa.String(36), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("captured_at", sa.DateTime(timezone=True)), sa.Column("released_at", sa.DateTime(timezone=True)), sa.Column("refunded_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("reference_type", "reference_id", name="uq_product_credit_reservation_reference"))
    op.create_index("ix_product_credit_reservations_status_expiry", "product_credit_reservations", ["status", "expires_at"])
    op.create_table("product_credit_reservation_allocations", sa.Column("id", sa.String(36), primary_key=True), sa.Column("reservation_id", sa.String(36), sa.ForeignKey("product_credit_reservations.id", ondelete="CASCADE"), nullable=False), sa.Column("bucket_id", sa.String(36), sa.ForeignKey("product_credit_buckets.id", ondelete="RESTRICT"), nullable=False), sa.Column("amount", sa.Integer(), nullable=False), sa.UniqueConstraint("reservation_id", "bucket_id", name="uq_product_credit_reservation_bucket"))
    op.create_table("product_signup_trial_grants", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("policy_id", sa.String(36), sa.ForeignKey("product_signup_trial_policies.id", ondelete="RESTRICT"), nullable=False), sa.Column("policy_key", sa.String(80), nullable=False), sa.Column("bucket_id", sa.String(36), sa.ForeignKey("product_credit_buckets.id", ondelete="RESTRICT"), nullable=False), sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("user_id", "policy_key", name="uq_product_signup_trial_grant"))
    op.create_table("product_billing_checkout_sessions", sa.Column("id", sa.String(36), primary_key=True), sa.Column("user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("offer_id", sa.String(36), sa.ForeignKey("product_billing_offers.id", ondelete="RESTRICT"), nullable=False), sa.Column("catalog_version_id", sa.String(36), sa.ForeignKey("product_billing_catalog_versions.id", ondelete="RESTRICT"), nullable=False), sa.Column("provider", sa.String(40), nullable=False), sa.Column("provider_session_id", sa.String(255)), sa.Column("status", sa.String(24), nullable=False), sa.Column("offer_snapshot", sa.JSON(), nullable=False), sa.Column("success_url", sa.Text(), nullable=False), sa.Column("cancel_url", sa.Text(), nullable=False), sa.Column("redirect_url", sa.Text()), sa.Column("idempotency_key", sa.String(255)), sa.Column("request_hash", sa.String(64)), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint("user_id", "idempotency_key", name="uq_product_billing_checkout_idempotency"), sa.UniqueConstraint("provider", "provider_session_id", name="uq_product_billing_provider_session"))
    op.create_table("product_payment_event_inbox", sa.Column("id", sa.String(36), primary_key=True), sa.Column("provider", sa.String(40), nullable=False), sa.Column("provider_event_id", sa.String(255), nullable=False), sa.Column("event_type", sa.String(120), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("raw_body_hash", sa.String(64), nullable=False), sa.Column("raw_payload", sa.JSON(), nullable=False), sa.Column("normalized_payload", sa.JSON(), nullable=False), sa.Column("raw_payload_expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("error", sa.JSON()), sa.Column("received_at", sa.DateTime(timezone=True), nullable=False), sa.Column("processed_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("provider", "provider_event_id", name="uq_product_payment_event"))
    op.create_index("ix_product_payment_event_status_received", "product_payment_event_inbox", ["status", "received_at"])
    op.create_table("product_billing_commands", sa.Column("id", sa.String(36), primary_key=True), sa.Column("actor_user_id", sa.String(36), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("command_type", sa.String(120), nullable=False), sa.Column("idempotency_key", sa.String(255), nullable=False), sa.Column("request_hash", sa.String(64), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("resource_type", sa.String(80)), sa.Column("resource_id", sa.String(36)), sa.Column("response_snapshot", sa.JSON()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("actor_user_id", "command_type", "idempotency_key", name="uq_product_billing_command_idempotency"))
    op.create_index("ix_product_billing_commands_actor_created", "product_billing_commands", ["actor_user_id", "created_at"])

    now = datetime(2026, 7, 14, tzinfo=timezone.utc)
    catalog_id = "00000000-0000-0000-0000-000000000001"
    op.bulk_insert(sa.table("product_billing_catalog_versions", sa.column("id", sa.String), sa.column("version_key", sa.String), sa.column("market", sa.String), sa.column("currency", sa.String), sa.column("status", sa.String), sa.column("effective_from", sa.DateTime(timezone=True)), sa.column("created_at", sa.DateTime(timezone=True)), sa.column("published_at", sa.DateTime(timezone=True)), sa.column("activation_reason", sa.Text)), [{"id": catalog_id, "version_key": "vn-v1", "market": "VN", "currency": "VND", "status": "active", "effective_from": now, "created_at": now, "published_at": now, "activation_reason": "Initial product catalog based on approved pricing"}])
    offer_table = sa.table("product_billing_offers", sa.column("id", sa.String), sa.column("catalog_version_id", sa.String), sa.column("code", sa.String), sa.column("display_name", sa.String), sa.column("offer_type", sa.String), sa.column("amount_minor", sa.Integer), sa.column("currency", sa.String), sa.column("billing_interval", sa.String), sa.column("credit_grant", sa.Integer), sa.column("active", sa.Boolean), sa.column("created_at", sa.DateTime(timezone=True)))
    offers = [("101", "SUB_60", "Student 60", "subscription", 49000, "month", 60), ("102", "SUB_150", "Career 150", "subscription", 99000, "month", 150), ("103", "SUB_350", "Pro 350", "subscription", 199000, "month", 350), ("104", "TOPUP_70", "Top-up 70", "topup", 70000, None, 70), ("105", "TOPUP_105", "Top-up 105", "topup", 100000, None, 105), ("106", "TOPUP_220", "Top-up 220", "topup", 200000, None, 220), ("107", "TOPUP_335", "Top-up 335", "topup", 300000, None, 335)]
    op.bulk_insert(offer_table, [{"id": "00000000-0000-0000-0000-000000000" + suffix, "catalog_version_id": catalog_id, "code": code, "display_name": name, "offer_type": kind, "amount_minor": amount, "currency": "VND", "billing_interval": interval, "credit_grant": credits, "active": True, "created_at": now} for suffix, code, name, kind, amount, interval, credits in offers])
    price_table = sa.table("product_feature_credit_prices", sa.column("id", sa.String), sa.column("catalog_version_id", sa.String), sa.column("feature_key", sa.String), sa.column("credit_cost", sa.Integer), sa.column("maximum_duration_minutes", sa.Integer), sa.column("change_reason", sa.Text), sa.column("created_at", sa.DateTime(timezone=True)))
    prices = [("201", "cv_upload", 0, None), ("202", "cv_analysis", 10, None), ("203", "job_search", 0, None), ("204", "interview", 25, 30)]
    op.bulk_insert(price_table, [{"id": "00000000-0000-0000-0000-000000000" + suffix, "catalog_version_id": catalog_id, "feature_key": key, "credit_cost": cost, "maximum_duration_minutes": duration, "change_reason": "Initial approved pricing", "created_at": now} for suffix, key, cost, duration in prices])
    op.bulk_insert(sa.table("product_signup_trial_policies", sa.column("id", sa.String), sa.column("policy_key", sa.String), sa.column("enabled", sa.Boolean), sa.column("trigger", sa.String), sa.column("credit_grant", sa.Integer), sa.column("valid_days", sa.Integer), sa.column("grants_per_user", sa.Integer), sa.column("policy_version", sa.String), sa.column("effective_from", sa.DateTime(timezone=True)), sa.column("reason", sa.Text), sa.column("created_at", sa.DateTime(timezone=True))), [{"id": "00000000-0000-0000-0000-000000000301", "policy_key": "SIGNUP_VERIFIED_EMAIL", "enabled": True, "trigger": "verified_email", "credit_grant": 50, "valid_days": 7, "grants_per_user": 1, "policy_version": "signup-trial-v1", "effective_from": now, "reason": "Initial approved signup trial", "created_at": now}])

    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE FUNCTION product_credit_ledger_immutable() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'credit ledger entries are immutable'; END; $$ LANGUAGE plpgsql")
        op.execute("CREATE TRIGGER trg_product_credit_ledger_immutable BEFORE UPDATE OR DELETE ON product_credit_ledger_entries FOR EACH ROW EXECUTE FUNCTION product_credit_ledger_immutable()")
    elif bind.dialect.name == "sqlite":
        op.execute("CREATE TRIGGER trg_product_credit_ledger_no_update BEFORE UPDATE ON product_credit_ledger_entries BEGIN SELECT RAISE(ABORT, 'credit ledger entries are immutable'); END")
        op.execute("CREATE TRIGGER trg_product_credit_ledger_no_delete BEFORE DELETE ON product_credit_ledger_entries BEGIN SELECT RAISE(ABORT, 'credit ledger entries are immutable'); END")


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS trg_product_credit_ledger_immutable ON product_credit_ledger_entries")
        op.execute("DROP FUNCTION IF EXISTS product_credit_ledger_immutable")
    elif bind.dialect.name == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS trg_product_credit_ledger_no_update")
        op.execute("DROP TRIGGER IF EXISTS trg_product_credit_ledger_no_delete")
    for table in ["product_billing_commands", "product_payment_event_inbox", "product_billing_checkout_sessions", "product_signup_trial_grants", "product_credit_reservation_allocations", "product_credit_reservations", "product_credit_ledger_entries", "product_credit_buckets", "product_credit_accounts", "product_billing_subscriptions", "product_signup_trial_policies", "product_feature_credit_prices", "product_billing_offers", "product_billing_catalog_versions"]:
        op.drop_table(table)
