"""product foundation primitives

Revision ID: 82fe1d807848
Revises: 20260707_0006
Create Date: 2026-07-14 19:25:10.901739
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '82fe1d807848'
down_revision: Union[str, Sequence[str], None] = '20260707_0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
